// <auto-generated />
// NullableAttribute/NullableContextAttribute polyfills for netstandard2.0/net472,
// matching the embedded shapes the C# compiler emits for nullable metadata.
#nullable enable

namespace System.Runtime.CompilerServices;

/// <summary>
/// Polyfill for nullable-metadata emission on targets without NullableAttribute.
/// </summary>
[AttributeUsage(AttributeTargets.All, AllowMultiple = false, Inherited = false)]
internal sealed class NullableAttribute : Attribute
{
    /// <summary>
    /// Nullable flags for the annotated symbol.
    /// </summary>
    public byte[] NullableFlags { get; }

    /// <summary>
    /// Single-flag nullable metadata.
    /// </summary>
    public NullableAttribute(byte flag)
    {
        NullableFlags = [flag];
    }

    /// <summary>
    /// Multi-flag nullable metadata.
    /// </summary>
    public NullableAttribute(byte[] flags)
    {
        NullableFlags = flags;
    }
}

/// <summary>
/// Polyfill for nullable-context metadata emission on targets without it.
/// </summary>
[AttributeUsage(AttributeTargets.Module | AttributeTargets.Class | AttributeTargets.Delegate | AttributeTargets.Interface | AttributeTargets.Method | AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
internal sealed class NullableContextAttribute(byte flag) : Attribute
{
    /// <summary>
    /// Nullable context flag for the annotated symbol.
    /// </summary>
    public byte Flag { get; } = flag;
}
